### ISSUE TITLE
Upload Widget - Layout broken for 768px wide

### ISSUE THREAD

**Issue by ShoryuKyzan** [cloudinary/cloudinary_npm#554] opened 2022-06-22 05:20 UTC
## Bug report for Cloudinary NPM SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.
Layout broken between 768 and 767 px. Broken for many tablet users most likely.

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Babel - Babel errors or cross browser issues
[ ] Performance - Performance issues
[X] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Incorrect Types - For typescript users who are having problems with our d.ts files
[ ] Other (Specify)

## Steps to reproduce
In Chrome devtools, use device simulator in responsive mode, and choose the bar for 768px.

## Error screenshots
![image](https://user-images.githubusercontent.com/32823296/174948882-ce2c11b0-0479-4cda-b8e5-549678f70084.png)

## Browsers
[X] Chrome
[ ] Firefox
[ ] Safari
[X] Other (Edge)
[ ] All
Didn't test others

## Versions and Libraries
Cloudinary_NPM SDK version 1.26.0, 1.30.0
Node - 16.15.0
NPM - 8.5.5

## Config Files
n/a, can't share, have confirmed version via package-lock.json tho.

## Repository
n/a, proprietary, can't share

**Comment by cloudy408** [comment] 2022-06-22 14:37
Hi Joseph,

Thanks for pointing out this issue, we were able to reproduce it.

The issue seems to be with the upload_widget, not the cloudinary_npm SDK. We have opened this as a bug for the upload_widget that is currently being prioritized for a fix.

Hope this helps, please let me know if you have any further questions.

Best regards,
John

**Comment by ShoryuKyzan** [comment] 2022-06-22 17:39
I'd like to subscribe to updates on that issue so I know when it's fixed. Tag me if its public? I cant seem to find that repo here.

**Comment by aleksandar-cloudinary** [comment] 2022-06-23 06:55
Hi @ShoryuKyzan - Thanks for following up about it. This GitHub thread is linked in our internal ticket and when there are updates to our internal ticket, we will be updating this thread as well so that it's all updated/in-sync.

**Comment by cloudinary-pkoniu** [comment] 2022-12-13 07:32
Hi @ShoryuKyzan, just wanted to notify you that the issue with broken layout should be already fixed. Can you verify that on your side so I can close this ticket (i.e. our communication channel for us)?

**Comment by ShoryuKyzan** [comment] 2022-12-13 23:22
@cloudinary-pkoniu I'll definitely put it on my todo list! We worked around it for the time being by just making the container a little wider or narrower when it was at that resolution.

**Closed** 2023-05-28 12:07 UTC
Labels: bug
