### ISSUE TITLE
Uploading using buffer or buffer.toString()

### ISSUE THREAD

**Issue by r3wt** [cloudinary/cloudinary_npm#130] opened 2017-01-11 04:00 UTC
first try:

```js
cloudinary.uploader.upload(req.files.avatar.data, function(result) { 
  console.log(result);
});
```
results in error message:
```
TypeError: file.match is not a function
at C:\<redacted>\node_modules\cloudinary\lib\uploader.js:67:34
```

second approach, converting the buffer to a string:
```js
cloudinary.uploader.upload(req.files.avatar.data.toString('utf8'), function(result) { 
  console.log(result);
});
```
results in error:
```
Error: Path must be a string without null bytes
       at nullCheck (fs.js:135:14)
       at Object.fs.open (fs.js:626:8)
       at ReadStream.open (fs.js:1936:6)
       at new ReadStream (fs.js:1923:10)
       at Object.fs.createReadStream (fs.js:1870:10)
       at post (C:\<redacted>\node_modules\cloudinary\lib\uploader.js:592:10)
```
IIRC, it looks like in the first instance its just not equipped to read a buffer (which it doesn't specify in docs). In second, it appears that it interpreted the stringified buffer as a file name and was a attempting to open the file and read it. This is the case I care about as the documentation on your website states that it is possible to upload file data directly. I would really prefer this approach as to storing the file to disk which creates alot of unnecessary io. So can you rectify this situation for me? What is the solution, as the documentation is certainly lacking, it doesn't even list the api for the library anywhere. the only documentation on your website is for ruby.

**Comment by Karayel** [comment] 2017-01-11 12:07
You have to use req.files.avatar.path instead of req.files.avatar.data or req.files.avatar.data.toString('utf8'). I think, it should work. 
You can see "image uplod" example in the following link . 

https://github.com/cloudinary/cloudinary_npm/tree/master/samples/photo_album

**Comment by r3wt** [comment] 2017-01-11 12:15
@Karayel i'm using `express-fileupload` which wraps busboy and stores files in memory at `req.files` object. thus avoid writing to the disk for what will be ultimately deleted anyway. The documentation of cloudinary states:
```
The following command uploads a local file to Cloudinary:

cloudinary.uploader.upload("my_picture.jpg", function(result) { 
  console.log(result) 
});

Alternatively, you can a specify a local path, a public HTTP URL, an S3 URL, an IO stream or an actual image file's data.
```
at the following page:
http://cloudinary.com/documentation/node_integration#upload_images

So, how do i do as it describes there, and upload the actual file data, which is what i have stored already in the buffer... perhaps you can pass me to someone who knows about this package?

**Comment by Karayel** [comment] 2017-01-11 12:22
In my experince, you can upload the actual file data like that.
var imageFile = req.files.image.path; //for your examle, this should be req.files.avatar.path
  // Upload file to Cloudinary
  cloudinary.uploader.upload(imageFile)
      .then(function (image) {
        console.dir(image);
        // If you want to save image to database. You can do it in here.
      });

**Comment by r3wt** [comment] 2017-01-11 12:30
dude, can you even read? I'm telling you, there is no such property as `req.files.avatar.path`. because it doesn't store anything to the disk.

**Comment by roeeba** [comment] 2017-01-12 18:56
@r3wt , can you please try this:

```
cloudinary.uploader.upload(req.files.avatar.data.toString('base64'), function(result) { 
  console.log(result);
});
```

**Comment by r3wt** [comment] 2017-01-12 19:17
@roeeba yes, that is exactly what i was looking for.

**Comment by r3wt** [comment] 2017-01-12 19:18
@roeeba it didn't work.

**Comment by r3wt** [comment] 2017-01-12 19:21
@roeeba didn't work. still tries to interpret it as a path and throws "ENAMETOOLONG"

**Comment by r3wt** [comment] 2017-01-12 19:21
I am working around for now by storing to a temp file and then cleaning it up after the upload to cloudinary succeeds.

**Comment by roeeba** [comment] 2017-01-17 19:03
Hi @r3wt , can you please share the full error message you've got (ENAMETOOLONG)?

**Comment by karthikiyengar** [comment] 2017-01-23 14:27
It's annoying to have to convert buffers to DataURIs or write them to disk before uploading them. This is an unnecessary perf slowdown and it would make sense for the upload method to support the direct use of Buffers.

**Comment by r3wt** [comment] 2017-01-23 14:34
@roeeba no, i just decided to stop using cloudinary.

**Comment by roeeba** [comment] 2017-02-01 19:22
@r3wt I'm sorry to hear that, we're always here for any further assistance if you'd reconsider. If you'd still want to resolve this, and if you could please share some more context, e.g., a sample Data URI, we'll be happy to do our best to reproduce the issue on our end.

@karthikiyengar Thank you very much for this feedback. I've forwarded your feedback to our engineers to review.

**Comment by leviwheatcroft** [comment] 2017-02-18 23:03
upload_stream is better suited to buffers

```
cloudinary.uploader.upload_stream((result) => console.log(result))
.end(req.files.avatar.data)
```

`end` in this case is just passing in your buffer and indicating there won't be any further writes to the stream.

`upload_stream` is just a [thin wrapper](https://github.com/cloudinary/cloudinary_npm/blob/master/src/uploader.coffee#L25) around `upload`, but it sets a `stream` flag. If you pass in a string `upload` is just going to treat it as a string and create a readStream from it.

**Comment by hades2510** [comment] 2017-06-14 14:14
just adding that if you only have one file using

`cloudinary.uploader.upload_stream( (result) => console.log(result) ).end( req.file.buffer )` will also work.

Notice the change fron **data** to **buffer**

**Comment by KromDaniel** [comment] 2017-10-07 19:31
Still the same issue
The JS docs are not helpful at all

from the docs

File:
```
the actual data (byte array buffer). 
For example, in some SDKs, this could be an IO input stream of the data (e.g., File.open(file, "rb")).
```

The Node.js documentation is very not documented. I had to guess many stuff my self and just started with debugging the Cloudinary object to find how to make it work

**Comment by maheshj567** [comment] 2017-10-08 05:23
I found a solution using `stream-buffers` module.

```
let imageBuffer; //buffer of an image
const stream = new s.ReadableStreamBuffer();
stream.put(imageBuffer);

let uploadStream = cloudinary.v2.uploader.upload_stream((error, result) => {
  console.log(error);
  
   // do your stuff
  console.log(result);
});

stream.pipe(uploadStream);
stream.stop();
```

**Comment by roeeba** [comment] 2017-10-08 13:35
Hi, @KromDaniel. We really appreciate your feedback! Could you please let us know what exactly is missing in our Node.js documentation so we'll make sure to fix it? Thanks!

**Comment by KromDaniel** [comment] 2017-10-08 16:09
Hey @roeeba ,
thanks for the comment

Here's some stuff I had to go through

https://cloudinary.com/documentation/node_image_upload#server_side_upload

cloudinary.v2.uploader.upload_stream : How to set options? Such as as {public_id} ?
Couldn't find anywhere, had to go to the source code and find my self


https://cloudinary.com/documentation/node_image_upload#direct_uploading_from_the_browser
Direct upload from the browser?
isn't that nodejs docs? confusing (browser != nodejs) + many jquery examples, what?

so there's a reference to the upload docs:

https://cloudinary.com/documentation/image_upload_api_reference#upload

> Parameter  = File
> Type = String
> Description:
> 1. a local file path (supported in SDKs only)
> 2. the actual data (byte array buffer). 
> 3. For example, in some SDKs, this could be an IO input stream of the data (e.g., File.open(file, "rb")).
> 4. the Data URI (Base64 encoded), max ~60MB (62,910,000 chars)
> 5. the remote FTP, HTTP or HTTPS URL address of an existing file
> an S3 URL of a whitelisted bucket
> 

2 and 4 doesn't work on the nodejs sdk and the nodejs docs refer to that.
How am I suppose to guess it? why is it documented then? and isn't that very basic thing to allow upload a Buffer? all the nodejs binary data works with buffers, isn't that basic? it only works with uploading a file with a given path to file but
If I already have the file stored on my server, then why do I need cloudinary?
and I guess that your nodejs sdk anyway reads the file as a buffer

Might be very helpful if:
1. support typescript definition
2. write documentation such as jsdoc  
    Example for amazing documentation
    https://draftjs.org/docs/api-reference-content-state.html#content
    Describes all the options in one place with some examples, at cloudinary the docs are just few examples.


So currently I find my self doing
`console.log(cloudinary)`
and getting a huge list  to some how reverse the SDK and understand alone how to use the SDK
 ```
  uploader:
      { unsigned_upload_stream: [Function],
        upload_stream: [Function],
        unsigned_upload: [Function],
        upload: [Function],
        upload_large_part: [Function],
        upload_large: [Function],
        upload_chunked: [Function],
        upload_chunked_stream: [Function],
        explicit: [Function],
        destroy: [Function],
        rename: [Function],
        text: [Function],
        generate_sprite: [Function],
        multi: [Function],
        explode: [Function],
        add_tag: [Function],
        remove_tag: [Function],
        remove_all_tags: [Function],
        add_context: [Function],
        remove_all_context: [Function],
        replace_tag: [Function],
        create_archive: [Function],
        create_zip: [Function],
        direct_upload: [Function],
        upload_tag_params: [Function],
        upload_url: [Function],
        image_upload_tag: [Function],
        unsigned_image_upload_tag: [Function] },
```

which might be helpful if it was documented somewhere
(couldn't find reference to most of it at any place)

For typescript, I've noticed that cloudinary-core does support typings
https://github.com/cloudinary/pkg-cloudinary-core
but as written at the example on the github:

```
var cl = cloudinary.Cloudinary.new();
cl.fromEnvironment();
```

then trying that (EXACTLY as written at the docs) 
```
var cl = cloudinary.Cloudinary.new();
cl.fromEnvironment(); 
```
I get typescript error

> **Property fromEnvironment does not exist on type 'Cloudinary'.**



This was really depressing
I really want to use the Cloudinary product and I find it really good, few years ago I used it
with the IOS sdk and it took me something like 1 hour until there was
images at the cloud. Now it took me more than half day when using the javascript sdk
because it is just not documented

Tried also direct upload from the browser but I didn't want that as solution and we're using React
which makes some stuff harder

I did see cloudinary React
https://github.com/cloudinary/cloudinary-react
which isn't mentioned at all on the cloudinary website
and isn't documented at all and the docs link doesn't have React at the list

**Comment by roeeba** [comment] 2017-10-09 08:57
Hey @KromDaniel, wow, thank you very much for the very detailed feedback. Really appreciated! I'm forwarding this to our documentation team to review. We'll do our best to improve the documentation as soon as we can.

**Comment by zacksayenko** [comment] 2017-10-10 01:10
@KromDaniel What was your solution to set options inside the upload_stream
I keep getting "Invalid image file" error { message: 'Invalid image file', http_code: 400 } when trying to send raw video/audio data.
I'm guessing that I need to set resource_type: 'raw', but don't see how to do that with the upload_stream.

Also completely agree, documentation is lacking, especially around uploading from buffer/stream, which I would think would be a very common use case for cloudinary.

**Comment by zacksayenko** [comment] 2017-10-10 01:25
OK, figured it out, just in case someone else needs it, here's what worked for me.

This uploads any file from buffer and stores it in a raw format
    
cloudinary.v2.uploader.upload_stream({resource_type: 'raw'}, function(error, result) {
            console.log(error);
            console.log(result);
        })
        .end(file.buffer);

**Comment by zacksayenko** [comment] 2017-10-10 06:17
It seems that if I add public_id to the options object it takes much longer to upload file than without it. Any ideas why that might be happening?

**Comment by mannieschumpert** [comment] 2017-11-12 02:59
Wow, it was challenging to track down how to upload a file from a buffer. :/

**Comment by glennreyes** [comment] 2017-12-15 18:45
Regarding Buffers, there's some syntax errors in one of your [examples in your doc](https://cloudinary.com/documentation/node_image_upload) you may want to fix:
![image](https://user-images.githubusercontent.com/5080854/34055616-4f8badea-e1d0-11e7-8404-e410985010fd.png)

**Comment by strausr** [comment] 2017-12-18 23:37
@glennreyes Great catch! I have forwarded this to our documentation team.

**Comment by zhihaochin** [comment] 2018-01-05 13:56
@zacksayenko thanks it worked for me! you are my hero

**Comment by adeelibr** [comment] 2018-02-21 13:00
The document still has the same error, any one reading this from the official cloudinary team. Kindly update your guides guys.

**Comment by yakirp** [comment] 2018-02-22 11:40
Hi @adeelibr ,

You are right and we are sorry for that. 
We will fix this ASAP.

Best,
Yakir

**Comment by eddyw** [comment] 2018-04-25 16:57
Is there anyway of setting the upload filename when uploading from buffer?
```javascript
        cloudinary.v2.uploader.unsigned_upload_stream(preset, (err_cloud, result) => { ... }).end(buffer)
```
We require the original file name, we switched from having to save to disk first to directly upload from buffer but I haven't found anywhere in the docs if it's supported. I did find an old PR that has no answers since 2017 that, I think, tries to add this option.

**Comment by shirlymanor** [comment] 2018-04-25 17:44
@eddyw You can set the public ID to be whatever you want by using the  public_id  parameter while uploading

```
function(buffer, filename, done) {
var stream = cloudinary.uploader.upload_stream(function(result) { done(result) }, {public_id: "my_picture"});
stream.write(data);
stream.end();
}
```

**Comment by eddyw** [comment] 2018-04-26 10:08
@shirlymanor we have the following settings in our preset:
```
Folder: pdf 
Use filename: false <<<
Disallow public ID: true <<<
Allowed formats: pdf 
Type: asset 
Access mode: public 
Format: pdf 
Invalidate: true 
Discard original file name: false <<<
```
As you can see, we want a randomly generated public id which will look similar to:

> ://res.cloudinary.com/[cloudname]/image/asset/**fl_attachment**/v[version]/pdf/[random public id].pdf

When uploading with `cloudinary.uploader.unsigned_upload('myfile.pdf',...)` and visiting the url, it will prompt the `Save File` dialog and the displayed name is the original name (e.g: myfile.pdf). However, buffers do not have a filename, so by default it assigns `file` as filename:
https://github.com/cloudinary/cloudinary_npm/blob/c6aa42b11f2b0b97d904f93d2c5794da8c0cdb1b/src/uploader.coffee#L279
The solution is pretty simple, it could check if `options.file` is defined, if not then assign `file` as filename.

**Comment by TheDancingCode** [comment] 2018-05-16 07:49
Although the method described above to upload buffers using `upload_stream` works, it feels a bit hacky. I still think the normal `upload` method should support buffers, like it says in the documentation. In that case, there should also be a filename option, similar to what's proposed in #176 for `upload_stream`.

**Comment by shirlymanor** [comment] 2018-05-30 21:29
Alternatively, you can use our fl_attachment feature that will download the image. Also, you can add your desired file name after the `:`. for example: http://res.cloudinary.com/demo/image/upload/fl_attachment:myfilename/sample.jpg

**Comment by darioblanco** [comment] 2018-08-29 15:11
An example with `async/await` and syntax from this century

```typescript
   import * as fs from 'fs';
   import { v2 as cloudinary } from 'cloudinary';

   async function main() {
     cloudinary.config({ cloud_name: 'blah', api_key: 'fake', api_secret: 'fake' });
     const buffer = fs.readFileSync('/my/fake/file/path.jpg');
     const result = await cloudinary.uploader.upload_stream({ public_id: 'my_picture' }).end(file);
   }

  main();
```

For the Typescript lovers, some minimal example type definitions that work for my use case (and the import stated before)

```typescript
declare module 'cloudinary' {
  export type Type = 'upload' | 'private' | 'authenticated';
  export type ResourceType = 'image' | 'raw' | 'video' | 'auto';

  export interface ConfigurationOptions {
    cloud_name: string;
    api_key: string;
    api_secret: string;
    secure?: boolean;
    upload_preset?: string;
    cdn_subdomain?: boolean;
    private_cdn?: boolean;
    cname?: string;
    secure_distribution?: string;
    static_image_support?: boolean;
    enhance_image_tag?: boolean;
  }

  export interface UploadOptions {
    public_id: string;
    tags: string[];
    folder: string;
    format: string;
    type: Type;
  }

  export interface UploadResult {
    public_id: string;
    version: number;
    signature: string;
    width: number;
    height: number;
    format: string;
    resource_type: ResourceType;
    created_at: string;
    tags: string[];
    bytes: number;
    type: string;
    etag: string;
    placeholder: boolean;
    url: string;
    secure_url: string;
    overwritten: boolean;
    original_filename: string;
    original_extension: string;
  }

  interface UploadStream {
    end(file: Buffer): UploadResult;
  }

  export type DestroyOptions = {
    resource_type?: ResourceType;
    type: Type;
    invalidate: boolean;
  };

  export type DestroyResult = {
    result: string;
  };

  export interface Uploader {
    upload(file: string | Buffer, options: UploadOptions): UploadResult;
    upload_stream(options: UploadOptions): UploadStream;
    destroy(public_id: string, options: DestroyOptions): DestroyResult;
  }

  export interface V2 {
    config(options: ConfigurationOptions): void;
    uploader: Uploader;
  }

  export const v2: V2;
}
```

I would create a `@types` project, but to be honest, it is quite some work and I think this is something the Cloudinary team should do.

**Comment by darioblanco** [comment] 2018-08-29 17:57
An example with async/await and syntax from this century (I needed to create a custom Promise). And I am surprised that the default `upload` method does not support this.

```typescript
import * as fs from 'fs';
import { v2 as cloudinary } from 'cloudinary';

function uploadStream(fileBuffer: Buffer, options: UploadOptions) {
  return new Promise((resolve, reject) => {
    // Sadly, this method does not support async/await
    cloudinary.uploader.upload_stream(options, (error, result) => {
      if (error) {
        reject(error);
      } else {
        resolve(result);
      }
    }).end(fileBuffer);
  });
}

async function main() {
  cloudinary.config({ cloud_name: 'blah', api_key: 'fake', api_secret: 'fake' });
  const buffer = fs.readFileSync('/my/fake/file/path.jpg');  // Should be async, but hey, it is just an example
  await uploadStream(buffer, { public_id: 'my_picture' });
}

main();
```

For the Typescript lovers, some minimal example type definitions that work for my use case (and the import stated before)

```typescript
declare module 'cloudinary' {
  export type Type = 'upload' | 'private' | 'authenticated';
  export type ResourceType = 'image' | 'raw' | 'video' | 'auto';

  export interface ConfigurationOptions {
    cloud_name: string;
    api_key: string;
    api_secret: string;
    secure?: boolean;
    upload_preset?: string;
    cdn_subdomain?: boolean;
    private_cdn?: boolean;
    cname?: string;
    secure_distribution?: string;
    static_image_support?: boolean;
    enhance_image_tag?: boolean;
  }

  export interface UploadOptions {
    public_id: string;
    tags: string[];
    folder: string;
    format: string;
    type: Type;
  }

  export interface UploadResult {
    public_id: string;
    version: number;
    signature: string;
    width: number;
    height: number;
    format: string;
    resource_type: ResourceType;
    created_at: string;
    tags: string[];
    bytes: number;
    type: string;
    etag: string;
    placeholder: boolean;
    url: string;
    secure_url: string;
    overwritten: boolean;
    original_filename: string;
    original_extension: string;
  }

  interface UploadStream {
    end(file: Buffer): UploadResult;
  }

  export type DestroyOptions = {
    resource_type?: ResourceType;
    type: Type;
    invalidate: boolean;
  };

  export type DestroyResult = {
    result: string;
  };

  export interface Uploader {
    upload(file: string | Buffer, options: UploadOptions): UploadResult;
    upload_stream(options: UploadOptions, cb: (err: Error, res: UploadResult) => void): any;
    destroy(public_id: string, options: DestroyOptions): DestroyResult;
  }

  export interface V2 {
    config(options: ConfigurationOptions): void;
    uploader: Uploader;
  }

  export const v2: V2;
}
```

I would create a @types project, but to be honest, it is quite some work and I think this is something the Cloudinary team should do.

**Comment by tocker** [comment] 2018-09-02 14:04
@darioblanco Thanks for the code snippet!

The default `upload` methods do support Promises and async/await, as do the admin APIs.

In the following example, `getResourcesIDs` and `getResourcesIDsP` are _functionally_ equivalent:

```javascript
const cloudinary = require('cloudinary').v2;
async function getResourcesIDs() {
  let {resources} = await cloudinary.api.resources();
  return resources.map(r=>r.public_id);
}

getResourcesIDs().then(console.log);

function getResourcesIDsP(){
  return cloudinary.api.resources()
    .then(({resources})=>resources.map(r=>r.public_id));
}
getResourcesIDsP().then(console.log);
```
 `upload_stream` doesn't return a promise like the other APIs, because it returns the actual stream. It's meant to allow the user to control the stream directly, for example performing multiple `write()` operations before `end()`. 
The callback receives the resource data once the upload is completed. Changing the interface will break backward compatibility but we're open to suggestions for the next major release!

In the meantime your solution should work well for a "single write" operation.

**Comment by darioblanco** [comment] 2018-09-02 14:06
Indeed, I use `async/await` for the default `upload` successfully. Thanks for the explanation about `upload_stream`! For my use case I only need one single write operation.

**Comment by roeeba** [comment] 2019-01-07 14:52
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2019-01-07 14:52 UTC
Labels: question

**Comment by bfunc** [comment] 2021-06-21 20:13
Thanks for the information. Solution for uploading image without creating temporary files works well, here is async version:
```

function uploadStreamAsync(buffer) {
  return new Promise((resolve, reject) => {
    cloudinary.v2.uploader
      .upload_stream(
        {
          resource_type: 'raw',
          format: 'jpg', // Convert to JPG. Without it image file will have no extension in url
        },
        function onEnd(error, result) {
          if (error) {
            return reject(error)
          }
          resolve(result)
        }
      )
      .end(buffer)
  })
}

// Usage
await uploadStreamAsync(formData.imageFieldName.data)

```

**Comment by Dalton-Klein** [comment] 2021-07-05 18:00
> OK, figured it out, just in case someone else needs it, here's what worked for me.
> 
> This uploads any file from buffer and stores it in a raw format
> 
> cloudinary.v2.uploader.upload_stream({resource_type: 'raw'}, function(error, result) {
> console.log(error);
> console.log(result);
> })
> .end(file.buffer);

THIS SAVED ME. I was having a problem getting my URL even though the upload was working. It was because the function has two arguments, error and result. You need to list result in the second argument slot. I was getting undefined, because it was printing the error, which was undefined.

**Comment by adilwahla** [comment] 2023-09-12 15:21
9/12/2023
i used small image to upload and it works
