### ISSUE TITLE
401 When trying uploadLarge() file with size more than max chunk size, on uploading second part.

### ISSUE THREAD

**Issue by chopikboy** [cloudinary/cloudinary_npm#82] opened 2016-01-21 17:05 UTC
401 When trying uploadLarge() file with size more than max chunk size, on uploading second part. RuntimeException : Server returned unexpected status code - 401 - {"error":{"message":"Invalid Signature b67b4d901dde99a4375e574d541e355d2e2e077b. String to sign - 'public_id=dropzone-signed-upload/cacya6j0bxwdazdwux9x&timestamp=1453395719&upload_preset=dropzone-signed-upload'."}}

**Comment by taragano** [comment] 2016-02-14 14:40
Hi,
Sorry for my response delay.

Can you please share a code snippet which we should be able to reproduce the issue with?

**Comment by taragano** [comment] 2016-08-22 23:44
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues

**Closed by taragano** 2016-08-22 23:44 UTC
Labels: question
