### ISSUE TITLE
Wrong function types API V2

### ISSUE THREAD

**Issue by protium-dev** [cloudinary/cloudinary_npm#314] opened 2019-11-11 21:13 UTC
I just noticed that in the last release (1.17.0), types for `cloudinary.uploader.upload_stream` are wrong. The function expect as first param `upload_preset: string`.
See https://github.com/cloudinary/cloudinary_npm/blob/master/types/index.d.ts#L841

**Comment by shirlymanor** [comment] 2019-11-11 22:36
Thank you for pointing it out for us! we will update it and let you know when it done.

**Comment by rgolea** [comment] 2019-12-22 23:41
I've got 2 issues with this. First of all, if you're going to put out there a v2, please update the package version to v2 so we know there are breaking changes. Also, all the types are wrong, not just `upload_stream`. They are kind of unusable. There are promises where there should be void, strings where callbacks... At this point it should be way easier just converting the files to ts and setting `noImplicitAny` in `tsconfig.json` as true and compile everything down to es5, es6 again. It should be a way easier work than trying to build them from scratch. Cheers!

**Comment by idobarnoam** [comment] 2019-12-23 10:00
Thanks @rgolea 

We have an open request with our dev team to look into this. 
We would take this internally and see how to approach it.

**Comment by rgolea** [comment] 2019-12-26 12:46
@idobarnoam @asisayag2 if you guys need to, I might take a look myself but I believe converting all files to `.ts` and bundling everything back to `.js` and `.map.js` will bring better typings not only for end users but better management for the project internally.

**Comment by idobarnoam** [comment] 2019-12-26 13:06
Thanks for offering @rgolea  

As there are several considerations to take into account at this point we would internally discuss this and see the best approach.

We would definitely keep in mind your offer :)

**Comment by sakulstra** [comment] 2020-01-21 13:06
We'd love to see that happen as well.

Currently this library is really hard to cope with due to wrong typings and other ts related problems like #326 (which breaks our build as we're using 3.7 internally).

**Comment by igy** [comment] 2020-01-21 15:03
Regarding the original issue here, a fix for the issue with upload_preset in the upload_stream method was merged earlier this week and should be in the next release.

If you want to pull the fix from master, details of the change can be found here: https://github.com/cloudinary/cloudinary_npm/pull/331

**Comment by rgolea** [comment] 2020-01-21 17:52
I'm finishing a project in about a month. Maybe then I can refactor the project to use typescript by default. It should render obsolete the `eslib-es5` folder and it should do the typings properly. If people want to use that fork, they're more than welcome. I will put it as a PR. If it gets merged, it would be awesome. I might also separate it in order to be able to publish it as `@cloudinary/...` so you can do an upload by just importing `@cloudinary/upload`. Hopefully I can bring something to the table here.

**Comment by igy** [comment] 2020-01-22 10:25
Hi Rares,
I can't speak as to whether that's something that will definitely work with the SDK team's roadmap for the SDK, but I'd certainly encourage you to make changes that work for you and your requirements; at the very least, as you said you can publish the changes yourself for other developers whose requirements align closely with yours

**Closed** 2020-02-05 11:40 UTC
Labels: bug

**Comment by jbjhjm** [comment] 2020-02-13 11:38
@igy You closed the issue, has it been fixed? As far as I see it's still unresolved.

**Comment by igy** [comment] 2020-02-13 11:52
As far as I'm aware this was resolved by the PR above, which was released in v1.19 of the SDK.
If you're still seeing issues with the typescript definitions, may I ask you to please open a new issue with the details?

It may be worth mentioning that the cause of this discrepancy was that the upload preset field was marked as mandatory in the definitions for the upload_stream function (which isn't the case), but it is required for unsigned_upload_stream if your upload will be unsigned.
