### ISSUE TITLE
err in callback function in upload instead of image.public_id use err.public_id. it works

### ISSUE THREAD

**Issue by poduvalmanu3** [cloudinary/cloudinary_npm#237] opened 2019-02-15 10:48 UTC

**Comment by aditimadan-Cloudinary** [comment] 2019-02-15 19:28
Can you please share the code and the error message you are seeing in order to debug this issue.

**Comment by poduvalmanu3** [comment] 2019-02-22 03:49
it"s not an error. in the call back function cloudinary.uploader.upload('pizza.jpg',function(err,image)
instead of image.public_id it should be err.public_id. just swap the place of  err and image as it should be the other way around.

**Comment by aditimadan-Cloudinary** [comment] 2019-02-25 22:49
That's the expected behavior if using v1 of the SDK. I will recommend using the v2 version which will look like `cloudinary.v2.uploader.upload('pizza.jpg',function(error,result)`

**Comment by poduvalmanu3** [comment] 2019-02-28 03:24
yeah i did use v1. thanks for the update

**Comment by strausr** [comment] 2019-11-24 10:26
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by strausr** 2019-11-24 10:26 UTC
