### ISSUE TITLE
Dependency on lodash throwing errors

### ISSUE THREAD

**Issue by ryan-ajmadison** [cloudinary/cloudinary_npm#183] opened 2018-02-23 15:10 UTC
My webpack is failing to compile and 'cloudinary-core' is throwing a bunch of errors regarding lodash:

ERROR in .//cloudinary-core/cloudinary-core.js Module not found: Error: Cannot resolve module 'lodash/isPlainObject' in /node_modules/cloudinary-core @ .//cloudinary-core/cloudinary-core.js 34:11-320

I've tried installing different versions of lodash and this package, but no dice.

My package.json currently:
"lodash": "^3.10.1",

**Comment by idobarnoam** [comment] 2018-02-26 15:14
@ryan-ajmadison 

I see that there is a duplicate issue [here](https://github.com/cloudinary/pkg-cloudinary-core/issues/21) which We're not quite sure what are the errors that are received.

Could you maybe clarify?

**Comment by curiousercreative** [comment] 2018-03-13 17:54
@idobarnoam this issue should be closed. It's for a different npm package: https://github.com/seokgyo/react-cloudinary/issues/7

**Comment by idobarnoam** [comment] 2018-03-18 12:18
@ryan-ajmadison 

In order for us to take a deeper look into this, could you share the `package.json` and the `webpack` config files?

Also if you could share a snippet that causes this behavior it would expedite the resolution.

**Comment by curiousercreative** [comment] 2018-03-20 02:03
@idobarnoam I work with @ryan-ajmadison and we've resolved this issue by updating `lodash` to latest version (4.1.x I believe). Our previous version of `lodash@3.10.1` appears to have been the cause (or perhaps we had two versions of `lodash`, one as production dep and one as development).

**Comment by idobarnoam** [comment] 2018-03-20 09:39
@curiousercreative Thanks for letting us know.

Glad to hear its working!

I'm closing this issue, but please feel free to open it again if you feel that it should remain open.

**Closed by idobarnoam** 2018-03-20 09:39 UTC
Labels: question
