### ISSUE TITLE
Able to upload corrupt image files using upload_stream

### ISSUE THREAD

**Issue by jwerre** [cloudinary/cloudinary_npm#222] opened 2018-12-04 00:15 UTC
I noticed the when uploading corrupt image files using `cloudinary.v2.uploader.upload` I get the correct error:

    { error: { message: 'Invalid image file', http_code: 400 } }

but if I upload the same image file using `cloudinary.v2.uploader.upload_stream` the file is uploaded without any issues.

**Comment by strausr** [comment] 2018-12-04 12:59
Can you please share with us the file you're uploading?

**Comment by jwerre** [comment] 2018-12-04 18:10
I used https://corrupt-a-file.net/

**Comment by strausr** [comment] 2018-12-05 12:55
We're unable to reproduce this. Can you please share exact reproduction steps along with the file?

**Comment by jwerre** [comment] 2018-12-05 18:19
const assert = require('assert'),
      cloudinary = require('cloudinary'),
      corruptImage = path.resolve(__dirname, 'corrupted.png'),
      options = {
        width: 720,
        height: 1000,
        resource_type: "auto",
        crop: "limit"
      };

    cloudinary.config({
      cloud_name: "",
      api_key: "",
      api_secret: "",
    });


    it("should error since file is corrupt", (done) => {
      cloudinary.v2.uploader.upload(corruptImage, options, function(err, result) {
        assert.ok(err);
        assert.ifError(result);
      });
    });

    it("should error since file is corrupt", (done) => {
      let readable, writable;
      readable = fs.createReadStream(corruptImage);
      writable = cloudinary.v2.uploader.upload_stream(options, function(err, result) {
        assert.ok(err);
        assert.ifError(result); // error
      });
      readable.pipe(writable);
    });

**Comment by shirlymanor** [comment] 2018-12-11 00:10
In order to provide a better feedback, can you please share the file that you're trying to upload? we can't use the  https://corrupt-a-file.net/ we need an actual file.

**Comment by strausr** [comment] 2019-01-07 16:35
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by strausr** 2019-01-07 16:35 UTC
Labels: question
