### ISSUE TITLE
root_folders ignores params

### ISSUE THREAD

**Issue by Vetm** [cloudinary/cloudinary_npm#291] opened 2019-08-22 12:51 UTC
The root_folders endpoint ignores any passed parameter. E.g. limiting the results or paginating.

Example:
`await cloudinary.v2.api.root_folders({'max_results': 1, 'next_cursor': nextCursor});`

This request will still return 2000 results instead of just one.

In our case this causes a huge problem because we have more than 2000 folders and can't iterate through them to get a complete list of our folders.

**Comment by igy** [comment] 2019-08-22 15:51
Hi Jonas

As I'm aware the server endpoint doesn't support those parameters which is why the SDK doesn't pass them to the server, and the documentation for the Admin API doesn't mention them - may I please ask is there an example you're working from, or something in one of our other SDKs showing pagination on the folders API?

It may be an oversight in this SDK or the documentation, but at the moment I'm not able to confirm the server-side API supports this either, so I may need to raise that as a feature request first
Thanks!

**Comment by igy** [comment] 2019-10-30 11:18
Hi Jonas,

Following up on this issue, I can confirm that the server-side behaviour doesn't currently support returning more than 2000 results, and pagination is not supported. We have a task open to add this, and I'll be sure to let you know if it's added.
Thanks,
Stephen

**Comment by strausr** [comment] 2020-03-11 08:52
Closing due to time elapse. We'll update if this feature is added to our roadmap

**Closed by strausr** 2020-03-11 08:52 UTC
Labels: question
